<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WlSjPrU' shared service.

return $this->privates['.service_locator.WlSjPrU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cartTools' => ['privates', 'App\\Tools\\Cart\\CartTools', 'getCartToolsService.php', true],
    'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService.php', true],
], [
    'cartTools' => 'App\\Tools\\Cart\\CartTools',
    'productRepository' => 'App\\Repository\\ProductRepository',
]);
