<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Tools\Cart\CartTools' shared autowired service.

include_once $this->targetDirs[3].'/src/Tools/Cart/CartTools.php';

return $this->privates['App\\Tools\\Cart\\CartTools'] = new \App\Tools\Cart\CartTools(($this->services['session'] ?? $this->load('getSessionService.php')), ($this->privates['App\\Repository\\ProductRepository'] ?? $this->load('getProductRepositoryService.php')));
