<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WhXQ59_' shared service.

return $this->privates['.service_locator.WhXQ59_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CartController::add' => ['privates', '.service_locator.I2iH6Ps', 'get_ServiceLocator_I2iH6PsService.php', true],
    'App\\Controller\\CartController::index' => ['privates', '.service_locator.I2iH6Ps', 'get_ServiceLocator_I2iH6PsService.php', true],
    'App\\Controller\\CartController::remove' => ['privates', '.service_locator.I2iH6Ps', 'get_ServiceLocator_I2iH6PsService.php', true],
    'App\\Controller\\ProductController::index' => ['privates', '.service_locator.WlSjPrU', 'get_ServiceLocator_WlSjPrUService.php', true],
    'App\\Controller\\ProductController::viewProduct' => ['privates', '.service_locator.WlSjPrU', 'get_ServiceLocator_WlSjPrUService.php', true],
    'App\\Controller\\CartController:add' => ['privates', '.service_locator.I2iH6Ps', 'get_ServiceLocator_I2iH6PsService.php', true],
    'App\\Controller\\CartController:index' => ['privates', '.service_locator.I2iH6Ps', 'get_ServiceLocator_I2iH6PsService.php', true],
    'App\\Controller\\CartController:remove' => ['privates', '.service_locator.I2iH6Ps', 'get_ServiceLocator_I2iH6PsService.php', true],
    'App\\Controller\\ProductController:index' => ['privates', '.service_locator.WlSjPrU', 'get_ServiceLocator_WlSjPrUService.php', true],
    'App\\Controller\\ProductController:viewProduct' => ['privates', '.service_locator.WlSjPrU', 'get_ServiceLocator_WlSjPrUService.php', true],
], [
    'App\\Controller\\CartController::add' => '?',
    'App\\Controller\\CartController::index' => '?',
    'App\\Controller\\CartController::remove' => '?',
    'App\\Controller\\ProductController::index' => '?',
    'App\\Controller\\ProductController::viewProduct' => '?',
    'App\\Controller\\CartController:add' => '?',
    'App\\Controller\\CartController:index' => '?',
    'App\\Controller\\CartController:remove' => '?',
    'App\\Controller\\ProductController:index' => '?',
    'App\\Controller\\ProductController:viewProduct' => '?',
]);
